name = "navibatch-homepage"
compatibility_date = "2024-06-02"

[env.production]
name = "navibatch-homepage"

# Pages 配置
pages_build_output_dir = "."

# 自定义域名配置（如果需要）
# route = "www.navibatch.com/*"

# 环境变量（如果需要）
[env.production.vars]
ENVIRONMENT = "production"
